### **NumPY**

In [ ]:
import numpy as np
l1=[10,20,30,40,50]   #single array
np.array(l1)



array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
n2=np.array([[10,20,30,40],[50,60,70,80]])
print(n2)


[[10 20 30 40]
 [50 60 70 80]]


# **Initializing numpy with zero**

In [ ]:
import numpy as np
n1=np.zeros((1,3))
print(n1)

[[0. 0. 0.]]


In [ ]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **Initializing numpy with specific number**

In [ ]:
import numpy as np
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

# **Initializing numpy array in range**

```
# This is formatted as code
```



In [ ]:
import numpy as np
np.arange(10,20)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
import numpy as np
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### **numpy for random no**

In [ ]:
import numpy as np
np.random.randint(100,500,10)

array([447, 293, 378, 281, 494, 198, 398, 119, 310, 153])

### **checking the shape of numpy arrays**

In [ ]:
import numpy as np
n1=np.array([[1,2,3,4],[4,3,2,1]])
print(n1)
#np.shape(n1)
n1.shape=(4,2)
print(n1)

[[1 2 3 4]
 [4 3 2 1]]
[[1 2]
 [3 4]
 [4 3]
 [2 1]]


**joining of array by numpy**

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([11,12,13,14])
np.vstack((n1,n1))           #vertically stack array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([11,12,13,14])
np.hstack((n1,n2))            #horizantally stack array

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14])

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([11,12,13,14,15])
np.column_stack((n1,n2))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15]])

Union/intersection/difference

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5,11,12])
n2=np.array([11,12,13,14,15])
np.intersect1d(n1,n2)

array([11, 12])

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5,11,12])
n2=np.array([11,12,13,14,15])
np.setdiff1d(n1,n2)

array([1, 2, 3, 4, 5])

# **for sum of two array**

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5,11,12])
n2=np.array([11,12,13,14,15])    #total sum of all no in these arrays
np.sum([n1,n1])

76

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([11,12,13,14,15])
#n3=np.sum(n1,n2, axis=0)
n3= np.sum([n1, n2], axis=0)   # to add column of array
print(n3)

[12 14 16 18 20]


In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([11,12,13,14,15])
#n3=np.sum(n1,n2, axis=0)
n3= np.sum([n1, n2], axis=1)   #to add row
print(n3)

[15 65]


**basic operation:Addiion/subtraction/division/multiplication**

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n1=n1+1
print(n1)

[2 3 4 5 6]


In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n1=n1-2
print(n1)

[-1  0  1  2  3]


In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5])
n1=n1*5
print(n1)

[ 5 10 15 20 25]


In [ ]:
import numpy as np
n1=np.array([5,10,15])
n1=n1%5
print(n1)

[0 0 0]


### **Mean/Median/standard deviation**

In [ ]:
n1=np.random.randint(1,100,10)
n1
np.mean(n1)


49.4

In [ ]:
n1=np.random.randint(1,100,10)
n1
np.median(n1)

65.5

In [ ]:
n1=np.random.randint(1,100,10)
n1
np.std(n1)

30.049292836937113

**Saving Numparray and load numpyarray**

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
np.save("my_nump",n1)

In [ ]:
# n1=np.array([1,2,3,4,5,6])
# np.save("my_nump",n1)
n2=np.load("my_nump.npy")
n2

array([1, 2, 3, 4, 5, 6])

In [ ]:
from karel.stanfordkarel import *
#from karel.stanfordkarel import *
def main():
  put_beeper()
  move()
  put_beeper()
  move()
  put_beeper()
  move()
  put_beeper()
  move()
  put_beeper()
  move()
  turn_left()
  turn_left()
if __name__ == "__main__":
    main()


ModuleNotFoundError: No module named 'karel'

In [ ]:
from karel.stanfordkarel import *

def main():
    # Put a beeper on the current square
    put_beeper()

    # Move Karel forward one square
    move()

    # Put a beeper on the current square
    put_beeper()

    # Move Karel forward one square
    move()

    # Put a beeper on the current square
    put_beeper()

    # Move Karel forward one square
    move()

    # Put a beeper on the current square
    put_beeper()

    # Move Karel forward one square
    move()

    # Put a beeper on the current square
    put_beeper()

    # Move Karel forward one square
    move()

    # Turn Karel around (180 degrees)
    turn_left()
    turn_left()

if __name__ == "__main__":
    main()

ModuleNotFoundError: No module named 'karel'